### ISSUE TITLE
Provide missing system messages

### ISSUE THREAD

**Issue by kghbln** [JeroenDeDauw/Validator#15]
The following system messages are missing as [seen here](https://www.semantic-mediawiki.org/wiki/Help:Ergebnisformat_googlemaps).
* [x] validator-type-dimension --> https://github.com/JeroenDeDauw/Validator/pull/16
* [x] validator-type-mapscircle-list --> https://github.com/JeroenDeDauw/Maps/issues/178
* [x] validator-type-mapsimageoverlay-list --> https://github.com/JeroenDeDauw/Maps/issues/178
* [x] validator-type-mapsline-list --> https://github.com/JeroenDeDauw/Maps/issues/178
* [x] validator-type-mapslocation-list --> https://github.com/JeroenDeDauw/Maps/issues/178
* [x] validator-type-mapslocation --> https://github.com/JeroenDeDauw/Maps/issues/178
* [x] validator-type-mapsrectangle-list --> https://github.com/JeroenDeDauw/Maps/issues/178
* [x] validator-type-wmsoverlay --> https://github.com/JeroenDeDauw/Maps/issues/178

Ideally I would like to reuse existing system messages with the same string such as e.g. "validator-type-string" to avoid "dupes" however I suspect that the message keys are constructed as a patchwork.

@JeroenDeDauw Any info on this?

**Comment by JeroenDeDauw** [comment]
Most of the `validator-type` messages are defined in https://github.com/JeroenDeDauw/Validator/tree/master/src. `validator-type-dimension` belongs there, as like the others, it's for a type defined in ParamProcessor. The others are (clearly) Maps specific, and should thus be defined there.

The keys are constructed in ParamProcessor, method `getTypeMessage` in https://github.com/JeroenDeDauw/ParamProcessor/blob/master/src/ParamDefinition.php. That stuff ought to be moved out of that component... though it might be easier to move the messages there. Not as correct, but solves half of the design issues.

**Comment by kghbln** [comment]
So these are indeed patchwork message keys. This issue looks like is should be split into two separate issues, one for ParamProcessor and one for Maps which have to be tackled to automatically solve this one?

**Comment by JeroenDeDauw** [comment]
Sounds good

**Comment by kghbln** [comment]
> Sounds good

@JeroenDeDauw Done

**Comment by kghbln** [comment]
> Sounds good

@JeroenDeDauw Done
